---
name: BurgerSpawners
main: Heisenburger69\BurgerSpawners\Main
version: 0.1.6
api: 3.0.0
author: Heisenburger69
website: https://github.com/Heisenburger69
description: Plugin implementing a Stackable Spawner System for PMMP

permissions:
  burgerspawners.silktouch:
    default: op
    description: Allows a user to use SilkTouch on Spawners
  burgerspawners.nosilktouch:
    default: false
    description: Allows a user to pickup Spawners even without Silk Touch

...
